- name: Restart Redis service
  ansible.builtin.service:
    name: redis-server
    state: restarted

- name: Restart prometheus service
  ansible.builtin.service:
    name: prometheus
    state: restarted
