---
- name: Download Prometheus
  ansible.builtin.get_url:
      url: "https://github.com/prometheus/prometheus/releases/download/v{{prometheus_version}}/prometheus-{{prometheus_version}}.linux-amd64.tar.gz"
      dest: "/tmp/prometheus.tar.gz"

- name: Extract Prometheus
  ansible.builtin.unarchive:
      src: "/tmp/prometheus.tar.gz"
      dest: "/tmp"
      remote_src: yes

- name: Remove Prometheus archive
  ansible.builtin.file:
      path: "/tmp/prometheus.tar.gz"
      state: absent

- name: Create directories for Prometheus
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: "0755"
  loop:
      - "/etc/prometheus"
      - "/var/lib/prometheus"

- name: Move Prometheus binaries and config
  ansible.builtin.command: "mv /tmp/prometheus-{{prometheus_version}}.linux-amd64/{{ item.src }} {{ item.dest }}"
  args:
      creates: "{{ item.dest }}/{{ item.src }}"
  loop:
      - { src: "prometheus", dest: "/usr/local/bin/" }
      - { src: "promtool", dest: "/usr/local/bin/" }
      - { src: "prometheus.yml", dest: "/etc/prometheus/" }
      - { src: "consoles", dest: "/etc/prometheus/" }
      - { src: "console_libraries", dest: "/etc/prometheus/" }

- name: Create prometheus user
  ansible.builtin.user:
      name: "prometheus"
      system: yes
      shell: "/bin/false"

- name: Set ownership of Prometheus directories
  ansible.builtin.file:
      path: "{{ item }}"
      owner: prometheus
      group: prometheus
  loop:
      - "/etc/prometheus"
      - "/var/lib/prometheus"

- name: Make prometheus a service
  ansible.builtin.template:
    src: prometheus.conf.j2
    dest: /etc/systemd/system/prometheus.service
    mode: 0664
    owner: ubuntu
    group: ubuntu

- name: Enable Prometheus service
  ansible.builtin.service:
      name: "prometheus"
      enabled: yes
  notify: Restart prometheus service
