---
- name: Install Apache and PHP modules
  ansible.builtin.apt:
    name:
      - wget
      - unzip
      - apache2
      - libgd3
      - php
      - php-apcu
      - php-bcmath
      - php-cli
      - php-common
      - php-curl
      - php-gd
      - php-gmp
      - php-imagick
      - php-intl
      - php-mbstring
      - php-mysql
      - php-zip
      - php-xml
    state: present
    update_cache: yes
  become: true
  notify:
        - Restart Apache service

- name: Download Nextcloud
  ansible.builtin.get_url:
    url: "https://download.nextcloud.com/server/releases/nextcloud-28.0.4.zip"
    dest: "/tmp/nextcloud.zip"
  become: true

- name: Unzip Nextcloud
  ansible.builtin.unarchive:
    src: "/tmp/nextcloud.zip"
    dest: "/var/www/html/"
    remote_src: yes
  become: true

- name: Copy files and directories from nextcloud to parent directory
  ansible.builtin.command: cp -r /var/www/html/nextcloud/. /var/www/html/

- name: Remove original nextcloud directory
  ansible.builtin.command: rm -r /var/www/html/nextcloud

- name: Set permissions for Nextcloud
  ansible.builtin.file:
    path: "/var/www/html"
    owner: www-data
    group: www-data
    recurse: yes
  become: true

- name: Enable Apache modules
  ansible.builtin.command:
    cmd: "a2enmod {{ item }}"
  loop:
    - rewrite
    - headers
    - env
    - dir
    - mime
  become: true
  notify:
        - Restart Apache service

- name: Install Nextcloud and configure database
  ansible.builtin.shell: | 
            cd /var/www/html
            sudo -u www-data php occ maintenance:install --database mysql --database-host {{ mariadb_host }} --database-port 3306 --database-name nextcloud --database-user nextclouduser --database-pass {{ mariadb_password }} --admin-user admin --admin-pass admin123
  become: true

- name: Update trusted domains in Nextcloud configuration
  lineinfile:
    path: /var/www/html/config/config.php
    line: "    1 => '193.225.250.156'"
    insertafter: "    0 => 'localhost',"
  notify:
        - Restart Apache service
