- name: Restart mariadb-server service
  ansible.builtin.service:
      name: mariadb
      state: restarted

- name: Restart prometheus service
  ansible.builtin.service:
      name: prometheus
      state: restarted