---
- name: Install Redis
  ansible.builtin.apt:
    name: redis-server={{redis_version}}
    state: present
    update-cache: yes
  become: true

- name: Modify Redis configuration
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: "^bind"
    line: "bind 0.0.0.0"
  become: true

- name: Enable Redis service
  ansible.builtin.service:
    name: redis-server
    enabled: yes
  become: true

- name: Restart Redis service
  ansible.builtin.service:
    name: redis-server
    state: restarted
  become: true

- name: Include Prometheus setup
  include_role:
    name: install_prometheus
  when: enable_grafana

- name: Include node_exporter setup
  include_role:
    name: install_node_exporter
  when: enable_grafana

- name: Add job to Prometheus configuration
  ansible.builtin.blockinfile:
    path: "/etc/prometheus/prometheus.yml"
    block: |
      {% filter indent(width=2, first=true) %}
      - job_name: 'remote_collector'
        scrape_interval: 10s
        static_configs:
          - targets: ['{{redis_host}}:9100']
      {% endfilter %}
    insertafter: EOF
    state: present
  notify: Restart prometheus service
  when: enable_grafana