---
- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install PyMySQL
  ansible.builtin.pip:
    name: pymysql
    state: present

- name: Install MariaDB
  ansible.builtin.apt:
    name: mariadb-server={{ mariadb_version }}
    state: present
    update_cache: yes
  become: true

- name: Mariadb security measures
  ansible.builtin.expect:
    command: mysql_secure_installation
    responses:
      "Enter current password for root": ""
      "Set root password": "n"
      "Remove anonymous users": "y"
      "Disallow root login remotely": "y"
      "Remove test database": "y"
      "Reload privilege tables now": "y"
    timeout: 1
  register: mariadb_security
  failed_when: "'... Failed!' in mariadb_security.stdout_lines"
  become: true

- name: Create Nextcloud Database
  ansible.builtin.mysql_db:
    name: "{{ nextcloud_database_name }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: true

- name: Create Nextcloud Database User with full privilege to Nextcloud User
  ansible.builtin.mysql_user:
    name: "{{ nextcloud_database_user }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "{{ nextcloud_host }}"
    password: "{{ nextcloud_database_password }}"
    priv: "{{ nextcloud_database_name }}.*:ALL"
    state: present
  become: true

- name: Replace bind-address in MariaDB config
  ansible.builtin.replace:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "127.0.0.1"
    replace: "0.0.0.0"
  become: true
  notify: Restart mariadb-server service

- name: Enable Mariadb service
  ansible.builtin.service:
    name: mariadb
    enabled: yes
  become: true
  notify:
    - Restart mariadb-server service

- name: Include Prometheus setup
  include_role:
    name: install_prometheus
  when: enable_grafana

- name: Include node_exporter setup
  include_role:
    name: install_node_exporter
  when: enable_grafana

- name: Add job to Prometheus configuration
  ansible.builtin.blockinfile:
    path: "/etc/prometheus/prometheus.yml"
    block: |
      {% filter indent(width=2, first=true) %}
      - job_name: 'remote_collector'
        scrape_interval: 10s
        static_configs:
          - targets: ['{{mariadb_host}}:9100']
      {% endfilter %}
    insertafter: EOF
    state: present
  notify: Restart prometheus service
  when: enable_grafana

- name: Grant privileges to the host for db backup
  ansible.builtin.mysql_user:
    name: "{{ nextcloud_database_user }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ nextcloud_database_password }}"
    priv: "*.*:ALL"
    host: "{{ mariadb_host }}"
    state: present
  become: true
  notify:
    - Restart mariadb-server service

- name: Add a backup script
  ansible.builtin.template:
    src: backup_script.sh.j2
    dest: /root/backup_script.sh
    mode: "700"

- name: Run backups at a specific time everyday
  ansible.builtin.cron:
    name: "backup cronjob"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    job: "/root/backup_script.sh"
